# Generated by Django 2.1.7 on 2019-03-11 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_auto_20190310_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ans',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='ans',
            name='user',
        ),
        migrations.AddField(
            model_name='ans',
            name='Question_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.Ask'),
        ),
        migrations.AddField(
            model_name='ans',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
